(#%require (lib "27.ss" "srfi"))
(random-source-randomize! default-random-source)

(define (play_guess target guess-count)
  (display "Guess a number from 1 to 100: ")
  (let ((guess (read)))
    (cond
      ((= guess target)
       (display "Correct! ")
       (display guess-count)
       (display " guesses... Please enter your name: ")
       (let ((name (read)))
         (display "Good game, ")
         (display name)))
      ((< guess target)
       (display "Higher... ")
       (play_guess target (+ guess-count 1)))
      ((> guess target)
       (display "Lower... ")
       (play_guess target (+ guess-count 1))))))
